---
###############################################################################
# The tuning values listed are for demonstration purposes only. 
# These values are a suggested starting point and are not definitive. 
# Customers should perform their own testing, to validate and verify their own
# settings, in order to meet their system needs.
###############################################################################
global:
  license: accept 
  images:
    registry: dxctektonspmregistry.azurecr.io  
    imageLibrary: tekton-pipelines
    imagePrefix: ''
    imageTag: latest
    pullPolicy: Always
  imagePullSecret:
    secretName: registry-access
    username: dxctektonspmregistry
  database:
    ## Database connection properties
    type: ORA
    dbName: oratest1
    hostname: 20.92.88.155
    port: 1521
    username: oraadmin
    credsSecretName: custom-db-secret
    wlp_psw: '{xor}Lz4sLCgwLTs='
    spm_psw: HlIxprF/66CsSSm6PON5+A==
    # Oracle Service name, where applicable
    serviceName: ''
    ssl:
      enabled: false
      # Name of the secret containing the database TLS certificate
      secretName: ''
      # Key in the above secret with the certificate
      secretKey: db2admin.arm
  ingress:
    enabled: true
    hostname: spm-openshift.apps.zv07q1kc.australiaeast.aroapp.io
  isam:
    enabled: false
  apps: 
     config:
       curam:
         enabled: true
         resources:
           limits:
             cpu: 2
             memory: 4Gi
           requests:
             cpu: 1
             memory: 2Gi
          ingressPath: /Curam
       rest:
         enabled: false
       citizenportal:
         enabled: false
       curamwebservices:
         enabled: false
       curambirtviewer:
         enabled: false
# Override values in 'apps' Chart
apps: 
   replicaCount: 1
   initialDelaySeconds: 60
   loginConfig:
     trace: true
   sessionConfig:
     sessionTimeout: 30m
     transactionTimeout: 3m
   defaultResources:
     requests:
       cpu: 0.5
       memory: 768Mi
     limits:
       cpu: 0.75
       memory: 1Gi
# Override values in 'batch' Chart
batch: 
   programs:
     queued:
       schedule: "*/30 * * * *"
# Override values in 'uawebapp' Chart
uawebapp: {}
#   replicaCount: 1
#   imageConfig:
#     library: ''
#     name: ''
#     tag: latest
#   readinessProbe:
#     path: /universal/
#   ingressPath: /universal
# Override values in 'web' Chart
web: 
   replicaCount: 1
   readinessProbe:
     path: /CuramStatic/
     ingressPath: /DEVCuramStatic
# Override values in 'xmlserver' Chart
xmlserver: {}
  replicaCount: 1
   jvm:
      maxMemory: '-Djava.maxmemory=768m'
      threadStackSize: '-Djava.thread.stack.size=-Xss4m'
   config:
      socketTimeout: 60000
      threadPoolQueueSize: 200
      threadPoolSize: 6
